/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lars' at '03.08.15 21:55' with Gradle 2.4
 *
 * @author lars, @date 03.08.15 21:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
